### ISSUE TITLE
Is there a CSV version of the Pandora data?

### ISSUE THREAD

**Issue by pudo** [ICIJ/offshoreleaks-data-packages#2]
Hey Miguel, sorry to bother about this. I was just wondering if there's a CSV or other tabular/JSON version of the Pandora Papers data that's pre-Neo4J? I saw that there's the `olddb` zip file, but that seems to merge up the data already, and has it interpreted as a Neo4J node graph. Perhaps there's more of a source form, e.g. companies, directors, shareholders? Thanks for any info!

**Comment by Dmirijs-Ozernovs** [comment]
There you can download zip with csv files: https://offshoreleaks.icij.org/pages/database

**Comment by pudo** [comment]
Uaaah I found it and forgot to close the ticket here! Sorry!
