### ISSUE TITLE
Do the _start and _end fields in the raw data refer to the id or node_id fields?

### ISSUE THREAD

**Issue by higherangelou** [ICIJ/offshoreleaks-data-packages#3]
I downloaded the raw data zip files and am trying to understand the data in postgres. I understand that the relationships table links all the others together, but which field on the other tabes maps to the _start and _end fields? It seems like it could be both the id and node_id fields. the id does not always start at 1. Thanks

**Comment by miguelfg** [comment]
Hi,

__start_ and __end_ ids belong to previous versions of csv exported files, and they were refering to the __id_ fields in the nodesXXX.csv files. We have improved this in the [current last csv](https://offshoreleaks-data.icij.org/offshoreleaks/csv/full-oldb.20220503.zip) downloadable package, and you would find: _node_id_start_ and _node_id_end_ columns in the relationships.csv file that refer to _node_id_ columns in nodesXXX.csv files.

We have also recently updated our neo4j dump files, so the three available versions to download for neo4j server 4.2.X, 4.3.X and 4.4.X contains the latest published data.

**Comment by matthewmcneely** [comment]
@miguelfg

> We have improved this in the [current last csv](https://offshoreleaks-data.icij.org/offshoreleaks/csv/full-oldb.20220503.zip) downloadable package

Does this mean this repo is not the "official" source for updates? I see on the current website, that link is now a few months newer than what is noted in your response.

Maybe that consolidated ZIP file could be added to this repo so that data "freshness" can be better monitored.

**Comment by miguelfg** [comment]
@matthewmcneely sorry for such late answer, but yes, this repo holds official data publications. While in the [website page](https://offshoreleaks-staging.cloud.icij.org/pages/database) you can find directly only the csv format kind, in this repo you have both, neo4j packages and zipped csv files.

**Comment by miguelfg** [comment]
I close this issue
