### ISSUE TITLE
Failed to load 'icij-offshoreleaks-42.dump' into 'neo4j' in 'Graph DBMS'

### ISSUE THREAD

**Issue by shuishbaevnuruddin** [ICIJ/offshoreleaks-data-packages#5]
Hello!

I met with problem that indicates as "Failed to load 'icij-offshoreleaks-42.dump' into 'neo4j' in 'Graph DBMS'"
I selected file into neo4j desktop, the file is called as 'icij-offshoreleaks-44.dump'. After I added that file to project and tried to "Create new DBMS from Dump" using that file. So while creating DBMS the problem was occured. So I habe no idea how to fix it.

**Comment by jodytng** [comment]
hi! what I did was to use an older version of the .dump-file and it should work :-) 

https://github.com/ICIJ/offshoreleaks-data-packages/blob/abaa8a4375aabc52470fb6ec34ecd8a0ee78b791/data/icij-offshoreleaks-44.dump

**Comment by miguelfg** [comment]
Sorry for late reply, @shuishbaevnuruddin the error mentions a different file version (42) from the one you said you imported to the project (44). 
In case the file was broken or corrupted, most likely, as jodytng mentioned you can try olders, and now newer, dumps from this [data/ folder](https://github.com/ICIJ/offshoreleaks-data-packages/tree/main/data).

If it keeps failing to you, please provide a screenshot
