### ISSUE TITLE
Broken hyperlink in Readme.adoc

### ISSUE THREAD

**Issue by netyaev** [ICIJ/offshoreleaks-data-packages#6]
Hello, In the README.adoc in the description of the Setup section for "3. Neo4j Aura" there is a broken link "https://console.neo4j.io/#import-instructions" returns the Not Found error. Thanks!

**Comment by miguelfg** [comment]
Sorry to being late to this. The link points to a Neo4j site that I do not have control, and basically I guess is an old guide to import a database in their Neo4j Aura service. This would be helpful if you had created an account there. I have not found an instructions guide in that service, but this one points to the importing action on your Neo4j Aura account: https://workspace-preview.neo4j.io/workspace/import

I'll remove the broken link for the moment. Thanks for pointing it out @netyaev
