### ISSUE TITLE
Failed to load 'icij-offshoreleaks-44.dump' into 'neo4j' in 'Graph DBMS'

### ISSUE THREAD

**Issue by SimG92** [ICIJ/offshoreleaks-data-packages#7]
Hello,
when I try to create a new DBMS using this dump, the DB results always offline. I tried with other dumps and I obtain the same result. I don't know how to fix this. I'm using a 5.5.0 DBMS

**Comment by miguelfg** [comment]
Hello @SimG92 , we are going to prepare newer dumps for 5.X Neo4j versions, in the meantime maybe you can try  to load it in a 4.4 DMBS.

**Comment by SimG92** [comment]
> Hello @SimG92 , we are going to prepare newer dumps for 5.X Neo4j versions, in the meantime maybe you can try to load it in a 4.4 DMBS.

I’ve tried with 4.4 too but I have the same issue

**Comment by miguelfg** [comment]
Hi again @SimG92 , i've pushed up a 5.13.0 version [here](https://github.com/ICIJ/offshoreleaks-data-packages/blob/main/data/icij-offshoreleaks-5.13.0.dump) . You have a latest 4.4.26 one too.

I hope it works well for you.

**Comment by moraesinvestigacoes** [comment]
olá, estou tentando baixar o dump 4.4 mas não estou conseguindo.

**Comment by miguelfg** [comment]
hello @moraesinvestigacoes , sorry for the late notice. Both the csv files and neo4j downloadables are linked in [this page](https://offshoreleaks.icij.org/pages/database) now.

**Comment by miguelfg** [comment]
Mark it as closed
