### ISSUE TITLE
Dumpfile is missing

### ISSUE THREAD

**Issue by truongkimson** [ICIJ/offshoreleaks-data-packages#8]
I'm unable to locate the dump file

**Comment by mossavatFontys** [comment]
where is the data folder??!

**Comment by pirhoo** [comment]
We moved the dumps out of this repository a while ago:

https://offshoreleaks.icij.org/pages/database

Direct links:

https://offshoreleaks-data.icij.org/offshoreleaks/neo4j/icij-offshoreleaks-4.4.26.dump
https://offshoreleaks-data.icij.org/offshoreleaks/neo4j/icij-offshoreleaks-5.13.0.dump
